hmcts/ccpayfr-shared-infrastructure

servicebus.tf
Merge after
https://github.com/hmcts/terraform-module-servicebus-subscription/pull/7
=> Infra for Retry

servicebus.tf
forcing terraform to refresh state
=> handling module dependency

servicebus.tf
Reverts hmcts/ccpayfr-shared-infrastructure#18
=> Revert "deleted servicebusconfig temporarily to force terraform state"

appgw.tf
Reverts hmcts/ccpayfr-shared-infrastructure#32
=> Revert "removed backend https config"

appgw.tf
fixing latest build failure on saat.
```
[ ] Yes
[x ] No
```
=> added common_tags

aat.tfvars, appgw.tf, prod.tfvars, saat.tfvars, sandbox.tfvars, sprod.tfvars, variables.tf
=> Paybbuble www prefix

key-vault.tf
passing common_tags to keyvault
```
[ ] Yes
[ x] No
```
=> passing common_tags to keyvault

appgw.tf, key-vault.tf, servicebus.tf
=> PAY-2182:WAF Configuration changes

appgw.tf
Activating WAF from detection to prevention
```
[ ] Yes
[ ] No
```
=> WAF pointed to master

output.tf
=> PAY-2663:Removed variable for app service plan

appgw.tf
=> CHG5000651 - Mitigate 502 errors

key-vault.tf
PR and changes are already discussed with Praveen from RPE.
Same changes are already tested on Demo as well
This is a follow-up PR of PR-60, so not extra approval required
=> PAY-3722: Referring newly created MI to fees-register kv

key-vault.tf
Group name updated
```
[ ] Yes
[x ] No
```
=> Group name updated.

Jenkinsfile_CNP
=> PAY-4612: build test

application-insights.tf, asp.tf, output.tf, servicebus.tf, state.tf, variables.tf
Remove ASP and outputs
```
[ ] Yes
[X] No
```
=> Remove ASP and outputs - Demo

servicebus.tf
All changes have been merged to master now, so I'm reverting the branches back to master.
```
[ ] Yes
[x] No
```
=> DTSPO-6371 - revert branches back to master

aat.tfvars, demo.tfvars, perftest.tfvars, prod.tfvars, servicebus.tf, variables.tf
=> Premiumservicebus

aat.tfvars, catalog-info.yaml, demo.tfvars, ithc.tfvars, perftest.tfvars, prod.tfvars, servicebus.tf, state.tf, variables.tf
Reverts hmcts/ccpayfr-shared-infrastructure#84
=> Revert "Servicebus premium changes"

state.tf, variables.tf
https://tools.hmcts.net/jira/browse/PAY-5797
Revert to last known good commit.
```
[ ] Yes
[x] No
```
=> PAY-5797: Revert back to last known good commit

catalog-info.yaml, emailAlert.tf
=> Updated slack channel

aat.tfvars, demo.tfvars, ithc.tfvars, key-vault.tf, perftest.tfvars, prod.tfvars, renovate.json, sandbox.tfvars
=> Remove old identity mentions

application-insights.tf, emailAlert.tf
https://tools.hmcts.net/jira/browse/DTSPO-15909
Updating azurerm_application_insights resource and replacing it with module terraform-module-application-insights
This will allow us to migrate Classic Application Insights using https://github.com/hmcts/app-insights-migration-tool as Classic Application Insights will deprecated and will be retired in February 2024.
=> DTSPO-15909 - migrated Application Insights

application-insights.tf, servicebus-premium.tf, state.tf
https://tools.hmcts.net/jira/browse/CME-332
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
=> CME-332: Update azurerm
